/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4O.DB4O;
import Business.Doctor.Doctor;
import Business.Donor.Donor;
import Business.Donor.DonorDirectory;
import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organizations;
//import Business.Organizations.PatientOrganization;
import Business.Patient.PatientDirectory;
import Business.Patient.patient;
import Business.User.User;
import Business.UserAccount.UserAccount;






//import UserInterface.Patient.Registrationform;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Sanskruti
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    private Doctor doctor;
    private patient patient;
    private PatientDirectory pDir;
    private DonorDirectory donordirectory;
    private Donor donor;
    private EcoSystem System;
  //  private final Random rand;
  //  private final int otpRange;
    //private EcoSystem ecosystem;
    private DB4O db40=DB4O.getInstance(); 
      public MainFrame() {
        initComponents();
       pDir = new PatientDirectory();
       donordirectory= new DonorDirectory();
        System=db40.retriveSystem();
        Logout.setEnabled(false);
        
        this.setSize(1680, 1050);
  //      rand = new Random();
  //      otpRange = 100000;
        //LoginBtn.setEnabled(false);
        //int otp1 ;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        RightPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userNameTextfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        unSeePwd = new javax.swing.JButton();
        forgotPwd = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        passwordTextfield = new javax.swing.JPasswordField();
        seePwd = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SplitPane.setDividerSize(2);

        RightPanel.setBackground(new java.awt.Color(0, 51, 51));
        RightPanel.setForeground(new java.awt.Color(255, 255, 255));
        RightPanel.setLayout(new java.awt.CardLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/optn.jpg"))); // NOI18N
        RightPanel.add(jLabel6, "card2");

        SplitPane.setRightComponent(RightPanel);

        leftPanel.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name ");

        userNameTextfield.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password  ");

        unSeePwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/unSee.png"))); // NOI18N
        unSeePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unSeePwdActionPerformed(evt);
            }
        });

        forgotPwd.setBackground(new java.awt.Color(0, 153, 153));
        forgotPwd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        forgotPwd.setForeground(new java.awt.Color(255, 255, 255));
        forgotPwd.setText("Forgot Password ?");
        forgotPwd.setBorder(new javax.swing.border.MatteBorder(null));
        forgotPwd.setBorderPainted(false);
        forgotPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwdActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(0, 153, 153));
        LoginBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        seePwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/See.png"))); // NOI18N
        seePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePwdActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 153, 153));
        Logout.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("LogOut");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ACCOUNT LOGIN !");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/login.png"))); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                                .addComponent(seePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unSeePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(forgotPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(userNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unSeePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(forgotPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(leftPanel);

        getContentPane().add(SplitPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePwdActionPerformed
        // TODO add your handling code here:
        passwordTextfield.setEchoChar((char)0);
    }//GEN-LAST:event_seePwdActionPerformed

    private void unSeePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unSeePwdActionPerformed
        passwordTextfield.setEchoChar('*');
    }//GEN-LAST:event_unSeePwdActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        
        String username =userNameTextfield.getText();
        //String pass = passwordTextfield.getText();
        
  //      List<patient> list = pDir.getPatientlist();
        char[] passwordCharArray= passwordTextfield.getPassword();
        String pwd= String.valueOf(passwordCharArray);
        UserAccount u =System.getUserAccountDirectory().authenticateUser(username, pwd);
        Enterprise enterprise =null;
        Organizations org =null;
        if(u==null)
        {
            for(Network network :System.getNetworkList())
            {
                for(Enterprise e:network.getEp().getEnterpriselist())
                {
                   u=e.getUserAccountDirectory().authenticateUser(username, pwd);
                   if(u==null)
                   {
                       for(Organizations o:e.getOrganizationdir().getOrganizationList())
                       {
                           u=o.getUserAccountDirectory().authenticateUser(username, pwd);
                           if(u!=null)
                           {
                               enterprise=e;
                               org=o;
                               break;
                           }
                       }
                   }
                   else 
                    {
                        enterprise=e;
                        break;
                    }
                if(org!=null)
                break;
                }
                if(enterprise!=null)
                    break;
            
            }
            
            
        }
        if(u==null)
        {
            JOptionPane.showMessageDialog(null,"Invalid Credentials");
            return;
        }
        else 
        {
            
            Logout.setEnabled(true);
            LoginBtn.setEnabled(false);
            userNameTextfield.setEnabled(false);
            passwordTextfield.setEnabled(false);
            CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add("workArea", u.getRole().createWorkArea(RightPanel, u, org, enterprise, System));
            layout.next(RightPanel);
        }
        /*
         if(((String)Roles.getSelectedItem()).equalsIgnoreCase("patient")){
            for(patient p : list){
                if((p.getUsername().equals(username))&& p.getPassword().equals(pwd)){
                    PatientManager pm=new PatientManager(RightPanel,pDir,System);
                    CardLayout layout=(CardLayout)RightPanel.getLayout();
                    RightPanel.add(pm);
                    layout.next(RightPanel);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Credentials ");
                }
            }
        }
        
        String UserName =userNameTextfield.getText();
        String password = passwordTextfield.getText();
        ArrayList<Donor> donorlist = donordirectory.getDonorlist();
        char[] passwordArray= passwordTextfield.getPassword();
        String password1= String.valueOf(passwordArray);
        UserAccount useraccount =System.getUserAccountDirectory().authenticateUser(UserName, password1);
        Enterprise enterprises =null;
        Organizations orgs =null;
        if(useraccount!=null)
        {
            CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add("workArea", useraccount.getRole().createWorkArea(RightPanel, useraccount, orgs, enterprises, System));
            layout.next(RightPanel);
        }
        else if(((String)Roles.getSelectedItem()).equalsIgnoreCase("donor")){
            for(Donor D : donorlist){
                if((D.getUserName().equals(UserName))&& D.getPassword().equals(password)){
                    SelectFunction sf=new SelectFunction(RightPanel,donordirectory,System);
                    CardLayout layout=(CardLayout)RightPanel.getLayout();
                    RightPanel.add(sf);
                    layout.next(RightPanel);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Invalid Credentials ");
                }
            }
        }
    */
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
            Logout.setEnabled(false);
            LoginBtn.setEnabled(true);
            userNameTextfield.setEnabled(true);
            passwordTextfield.setEnabled(true);
            
            userNameTextfield.setText(null);
            passwordTextfield.setText(null);
            
            RightPanel.removeAll();
            JPanel blankJP = new JPanel();
            
           
            
            RightPanel.add("blank",blankJP);
            CardLayout cardLayout=(CardLayout)RightPanel.getLayout();
            cardLayout.next(RightPanel);
            db40.storeSystem(System);
       
    }//GEN-LAST:event_LogoutActionPerformed

    private void forgotPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwdActionPerformed
        // TODO add your handling code here:
        UserAccount acc =new UserAccount();
        int found =0;
        if(userNameTextfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"UserName Field Is empty !");
            return;
        }
        else{
             for(Network network :System.getNetworkList()){
                for(Enterprise e:network.getEp().getEnterpriselist()){
                    for(Organizations o:e.getOrganizationdir().getOrganizationList()){
                    for(UserAccount ua :o.getUserAccountDirectory().getUserAccounts()){
                        if(ua.getUsername().equals(userNameTextfield.getText())){
                            
                            found =1;
                            acc=ua;
                            
                        }
                    }
                }
                }  
        }
             if(found==1){
        ForgotPwd fpwd= new ForgotPwd(RightPanel,userNameTextfield.getText(),System);
       CardLayout cardLayout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(fpwd);
            cardLayout.next(RightPanel);
             }
             else
                 JOptionPane.showMessageDialog(null,"Invalid UserName !");
    }//GEN-LAST:event_forgotPwdActionPerformed
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton forgotPwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPasswordField passwordTextfield;
    private javax.swing.JButton seePwd;
    private javax.swing.JButton unSeePwd;
    private javax.swing.JTextField userNameTextfield;
    // End of variables declaration//GEN-END:variables
}
