/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TC;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author meetveera
 */
public class TCWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TCWorkAreaJPanel
     */
    private JPanel RightPanel;
    private Enterprise enterprise;
    //EcoSystem Business;
    public TCWorkAreaJPanel(JPanel RightPanel, Enterprise enterprise) {
        initComponents();
        this.RightPanel=RightPanel;
        this.enterprise=enterprise;
        
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegisteraDoc = new javax.swing.JButton();
        ManageTcBtn1 = new javax.swing.JButton();
        manageDoc = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSPLANTATION CENTER WORKAREA");

        RegisteraDoc.setBackground(new java.awt.Color(0, 153, 204));
        RegisteraDoc.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        RegisteraDoc.setForeground(new java.awt.Color(255, 255, 255));
        RegisteraDoc.setText("ADD A DOCTOR");
        RegisteraDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisteraDocActionPerformed(evt);
            }
        });

        ManageTcBtn1.setBackground(new java.awt.Color(0, 153, 204));
        ManageTcBtn1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        ManageTcBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ManageTcBtn1.setText("MANAGE ORGANIZATION");
        ManageTcBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageTcBtn1ActionPerformed(evt);
            }
        });

        manageDoc.setBackground(new java.awt.Color(0, 153, 204));
        manageDoc.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        manageDoc.setForeground(new java.awt.Color(255, 255, 255));
        manageDoc.setText("MANAGE DOCTOR");
        manageDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisteraDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageTcBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ManageTcBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisteraDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisteraDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisteraDocActionPerformed
        // TODO add your handling code here:
        AddDoctorJPanel ad= new AddDoctorJPanel(RightPanel,enterprise.getOrganizationdir());
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(ad);
            layout.next(RightPanel);
    }//GEN-LAST:event_RegisteraDocActionPerformed

    private void ManageTcBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageTcBtn1ActionPerformed
        // TODO add your handling code here:
        ManageOrganization mo=new ManageOrganization(RightPanel,enterprise.getOrganizationdir());
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(mo);
            layout.next(RightPanel);
    }//GEN-LAST:event_ManageTcBtn1ActionPerformed

    private void manageDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDocActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel md=new ManageDoctorJPanel(RightPanel,enterprise);
        CardLayout layout=(CardLayout)RightPanel.getLayout();
            RightPanel.add(md);
            layout.next(RightPanel);
    }//GEN-LAST:event_manageDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageTcBtn1;
    private javax.swing.JButton RegisteraDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDoc;
    // End of variables declaration//GEN-END:variables
}
