/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.DoctorOrganization;
import Business.Organizations.Organizations;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientCostWorkRequest;
import Business.WorkQueue.PatientOrganWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanskruti
 */
public class CostRequest extends javax.swing.JPanel {

    /**
     * Creates new form CostRequest
     */
     private JPanel RightPanel;
    private EcoSystem system;
    private UserAccount account;
    private Enterprise enterprise;
    private Enterprise TC;
    private Network lc;
    private Network network;
    public CostRequest(JPanel RightPanel, UserAccount account, Enterprise enterprise,EcoSystem system,Network lc, Enterprise TC) {
        initComponents();
        this.RightPanel = RightPanel;
        this.account = account;
        this.enterprise=enterprise;
        this.system=system;
        this.network=network;
        this.lc=lc;
         MoneyClaim.setEnabled(false);
        this.TC=TC;
        populateTF();
        
        
    }
    public void populateTF()
    {
        DefaultTableModel model = (DefaultTableModel) Cost.getModel();
        model.setRowCount(0);
        for(WorkRequest w:account.getCq().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = w.getMessage();
            row[1] = w.getReceiver();
            row[2] = w.getStatus();
            String result = ((PatientCostWorkRequest) w).getTreatmentCost();
            row[3] = result == null ? "Waiting" : result; 
            if(result==null){
                MoneyClaim.setEnabled(false);
            }
            else
            MoneyClaim.setEnabled(true);
       //     row[0] = w.getStatus();
       //     row[1] = w.getMessage();
            model.addRow(row);
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Cost = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Organ = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        MoneyClaim = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        Cost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organ", "Receiver", "status", "Cost"
            }
        ));
        jScrollPane2.setViewportView(Cost);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REQUEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Organ.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        Organ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Kidney", "Lungs", "Liver", "Intestine", "Heart", "Pancrease" }));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REQUIRED ORGAN :");

        MoneyClaim.setBackground(new java.awt.Color(0, 102, 102));
        MoneyClaim.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        MoneyClaim.setForeground(new java.awt.Color(255, 255, 255));
        MoneyClaim.setText("MONEY CLAIM");
        MoneyClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyClaimActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COST ESTIMATION REQUEST");

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(207, 207, 207)
                                .addComponent(MoneyClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(63, 63, 63)
                                    .addComponent(Organ, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Organ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MoneyClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Organ.getSelectedItem().equals("--Select--")){
            JOptionPane.showMessageDialog(null,"Please select an organ !");
            return;
            
        }
        
        else{
        Organizations org =null;
        for(Network network :system.getNetworkList()){
            for(Enterprise e:network.getEp().getEnterpriselist()){
                for(Organizations o:e.getOrganizationdir().getOrganizationList()){
                    if(network.equals(lc)){
                        if(e.equals(TC)){
                            if(o instanceof DoctorOrganization)
                                org=o;
                            break;
                        }
                    }
                }
            }
        }
        if(org !=null){
            
            String message = (String)Organ.getSelectedItem();
            PatientCostWorkRequest request= new PatientCostWorkRequest();
            request.setMessage(message);
            request.setSender(account);
       //     request.setMessage("whats the cost ?");
            request.setStatus("Sent");
            org.getCostEstimation().getWorkRequestList().add(request);
            account.getCq().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null,"cost estimation sent !");
            populateTF();
            try{
            Email emailConfig= new Email();
            Properties smtpProperties = emailConfig.loadProperties();
            String email = account.getUsername();
            emailConfig.sendEmail(smtpProperties, email, "Request Initiated", "Your request has being sent to the Transplantation center");
        }
            catch(Exception ex){
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed
        if(org ==null)
        {
            JOptionPane.showMessageDialog(null,"There was no Doctors Organization in the Transplantation Center  you have Selected !");
            return;
        }
        }
    
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MoneyClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyClaimActionPerformed
        // TODO add your handling code here:
        /*if(Cost.getSelectedRow()>0){
            String status =(String)Cost.getValueAt(Cost.getSelectedRow(),3);
            if(!status.equals("Waiting")){
                MoneyClaim.setEnabled(true);
            }
        }*/
        int selectedRow=Cost.getSelectedRow();
        if(selectedRow>=0){
        Insurance i =new Insurance(RightPanel, account,enterprise,network,system,lc,TC,(String)Cost.getValueAt(Cost.getSelectedRow(),3));
                CardLayout layout=(CardLayout)RightPanel.getLayout();
                RightPanel.add(i);
                layout.next(RightPanel);
        }
        else
            JOptionPane.showMessageDialog(null,"Select a row !");
        
            
        
        
        
    }//GEN-LAST:event_MoneyClaimActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Cost;
    private javax.swing.JButton MoneyClaim;
    private javax.swing.JComboBox<String> Organ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
