/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Network.*;
import Business.Enterprise.Enterprise;
import Business.Enterprise.TCEnterprise;
import Business.Organizations.Organizations;
import Business.Organizations.PatientOrganization;
//import Business.Organizations.PatientOrganization;
import Business.Enterprise.UserEnterprise;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author meetveera
 */
//Trying again
public class PatientManager extends javax.swing.JPanel {

    /**
     * Creates new form PatientManager
     */
    private JPanel RightPanel;
    private UserAccount account;
    private Enterprise enterprise;
    private PatientDirectory pDir;
    private EcoSystem System;
   // private Organizations organization;
    private PatientOrganization organization;

    public PatientManager(JPanel RightPanel, UserAccount account, PatientOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.RightPanel=RightPanel;
        this.account = account;
        this.organization = organization;
        this.System=business;
        this.enterprise = enterprise;
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RequestOrgan = new javax.swing.JButton();
        ViewDetails = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        RequestOrgan.setBackground(new java.awt.Color(0, 102, 102));
        RequestOrgan.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        RequestOrgan.setForeground(new java.awt.Color(255, 255, 255));
        RequestOrgan.setText("REQUEST FOR ORGAN");
        RequestOrgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOrganActionPerformed(evt);
            }
        });

        ViewDetails.setBackground(new java.awt.Color(0, 102, 102));
        ViewDetails.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        ViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        ViewDetails.setText("VIEW DETAILS");
        ViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ACCOUNT MANAGER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Gabriola", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RequestOrgan, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addComponent(RequestOrgan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RequestOrganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestOrganActionPerformed

      CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add("OrganRequest", new OrganRequest(RightPanel, account,enterprise, System));
      layout.next(RightPanel);
    }//GEN-LAST:event_RequestOrganActionPerformed

    private void ViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add("ViewDetails", new ViewDetails(RightPanel, account,enterprise, System));
      layout.next(RightPanel);
       
    }//GEN-LAST:event_ViewDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) RightPanel.getLayout();
      RightPanel.add( "PatientAccountManager",new PatientAccountManager(RightPanel, account, enterprise));
      layout.next(RightPanel);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestOrgan;
    private javax.swing.JButton ViewDetails;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
