/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author meetveera
 */
public class PatientAccountManager extends javax.swing.JPanel {

    /**
     * Creates new form PatientAccountManager
     */
    private JPanel RightPanel;
    private UserAccount account;
    private Enterprise enterprise;
    public PatientAccountManager(JPanel RightPanel, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.RightPanel = RightPanel;
        this.account = account;
        this.enterprise = enterprise;
        usernameJTextField.setEditable(false);
        usernameJTextField.setText(account.getUsername());
        passwordJTextField1.setEditable(false);
        newpasswordJTextField.setEditable(false);
        SecurityAnsTxt.setEditable(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        SecurityQuestion = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        SecurityAnsTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackJButton = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Changepassword = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        submitPassword1 = new javax.swing.JButton();
        SecurityJButton = new javax.swing.JButton();
        passwordJTextField1 = new javax.swing.JPasswordField();
        newpasswordJTextField = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel26.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SECURITY QUESTION :");

        SecurityQuestion.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        SecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mothers name ?", "What was the name of your elementary / primary school?", "What street did you live on in third grade?", "What is your oldest cousin's first and last name?" }));

        jLabel27.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SECURITY ANSWER :");

        SecurityAnsTxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD :");

        usernameJTextField.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME :");

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NEW PASSWORD : ");

        BackJButton.setBackground(new java.awt.Color(0, 102, 102));
        BackJButton.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        BackJButton.setForeground(new java.awt.Color(255, 255, 255));
        BackJButton.setText("<<BACK");
        BackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJButtonActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(0, 102, 102));
        Submit.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Changepassword.setBackground(new java.awt.Color(0, 102, 102));
        Changepassword.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        Changepassword.setForeground(new java.awt.Color(255, 255, 255));
        Changepassword.setText("Change Password");
        Changepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangepasswordActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGE THE PATIENT ACCOUNT");

        submitPassword1.setBackground(new java.awt.Color(0, 102, 102));
        submitPassword1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        submitPassword1.setForeground(new java.awt.Color(255, 255, 255));
        submitPassword1.setText("SUBMIT");
        submitPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPassword1ActionPerformed(evt);
            }
        });

        SecurityJButton.setBackground(new java.awt.Color(0, 102, 102));
        SecurityJButton.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        SecurityJButton.setForeground(new java.awt.Color(255, 255, 255));
        SecurityJButton.setText("Set Security Question");
        SecurityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(BackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SecurityAnsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(SecurityJButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(newpasswordJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(passwordJTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Changepassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(passwordJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newpasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Changepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecurityAnsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
     //   String newpass = newpasswordJTextField.getText();
     //   account.setPassword(newpass);
        if(SecurityAnsTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter the security answer first!!");
            return;
        }
        else{
        account.setSecurityQ((String)SecurityQuestion.getSelectedItem());
        account.setSecurityA(SecurityAnsTxt.getText());
        account.setVal(1);
    //    JOptionPane.showMessageDialog(null, "password changed successfully");
        JOptionPane.showMessageDialog(null, "Security Question added successfully");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ChangepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangepasswordActionPerformed
        // TODO add your handling code here:
        passwordJTextField1.setEditable(true);
        newpasswordJTextField.setEditable(true);
        
    }//GEN-LAST:event_ChangepasswordActionPerformed

    private void BackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJButtonActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_BackJButtonActionPerformed

    private void submitPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitPassword1ActionPerformed
        // TODO add your handling code here:
        String pass = passwordJTextField1.getText();
        if(!(pass.equals(account.getPassword()))){
            JOptionPane.showMessageDialog(null, "original password not correct");
            return;
        }
        else {
             String newpass = newpasswordJTextField.getText();
             account.setPassword(newpass);
            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
        }
    }//GEN-LAST:event_submitPassword1ActionPerformed

    private void SecurityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityJButtonActionPerformed
        // TODO add your handling code here:
        SecurityAnsTxt.setEditable(true);
        SecurityQuestion.setEnabled(true);
    }//GEN-LAST:event_SecurityJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJButton;
    private javax.swing.JButton Changepassword;
    private javax.swing.JTextField SecurityAnsTxt;
    private javax.swing.JButton SecurityJButton;
    private javax.swing.JComboBox<String> SecurityQuestion;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField newpasswordJTextField;
    private javax.swing.JPasswordField passwordJTextField1;
    private javax.swing.JButton submitPassword1;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
