/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Donor;

import Business.EcoSystem;
import Business.Email.Email;
import Business.Enterprise.Enterprise;
import Business.Enterprise.TCEnterprise;
import Business.Network.Network;
import Business.Organizations.DoctorOrganization;
import Business.Organizations.Organizations;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorOrganWorkRequest;
import Business.WorkQueue.PatientOrganWorkRequest;
import Business.WorkQueue.WorkRequest;

import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharw
 */
public class OrganDonate extends javax.swing.JPanel {

    /**
     * Creates new form OrganDonate
     */
    private JPanel RightPanel;
    private EcoSystem System;
    private UserAccount account;
    private Enterprise enterprise;
    public OrganDonate(JPanel RightPanel, UserAccount account, Enterprise enterprise, EcoSystem System) {
        initComponents();
        this.RightPanel = RightPanel;
        this.account = account;
        this.enterprise = enterprise;
        this.System=System;
        //submitbtn.setEnabled(false);
        populateDonateTable();
        populateLocation();
    }

    

    public void populateDonateTable(){
        DefaultTableModel model = (DefaultTableModel) DonorWorkRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((DonorOrganWorkRequest) request).getOrgan();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
    }
    
    public void populateLocation(){
        for (Network network : System.getNetworkList()) {
            DonorLocationComboBox.addItem(network);
        }
    }
    
    public void populateTC(Network network){
        DonorTCComboBox.removeAllItems();
        for(Enterprise e: network.getEp().getEnterpriselist())
            if(e instanceof TCEnterprise)
                  DonorTCComboBox.addItem(e);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DonorWorkRequestJTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        OrganList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        DonorLocationComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        DonorTCComboBox = new javax.swing.JComboBox();
        sugarlabel = new javax.swing.JLabel();
        BPLabel = new javax.swing.JLabel();
        druglabel = new javax.swing.JLabel();
        bloodlabel = new javax.swing.JLabel();
        othertxt = new javax.swing.JTextField();
        drugtxt = new javax.swing.JTextField();
        BPTxt = new javax.swing.JTextField();
        sugartxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DONATE ORGANS :");

        DonorWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(DonorWorkRequestJTable);

        backbtn.setBackground(new java.awt.Color(0, 153, 153));
        backbtn.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        refreshbtn.setBackground(new java.awt.Color(0, 153, 153));
        refreshbtn.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        refreshbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshbtn.setText("REFRESH ");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        submitbtn.setBackground(new java.awt.Color(0, 153, 153));
        submitbtn.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitbtn.setText("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        OrganList.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        OrganList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Kidney", "Lungs", "Liver", "Intestine", "Heart", "Pancrease" }));

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOCATION  :");

        DonorLocationComboBox.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        DonorLocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorLocationComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSPLANTATION CENTER :");

        DonorTCComboBox.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        sugarlabel.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        sugarlabel.setForeground(new java.awt.Color(255, 255, 255));
        sugarlabel.setText("BLOOD SUGAR :");

        BPLabel.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        BPLabel.setForeground(new java.awt.Color(255, 255, 255));
        BPLabel.setText("BLOOD PRESSURE :");

        druglabel.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        druglabel.setForeground(new java.awt.Color(255, 255, 255));
        druglabel.setText("DRUG TEST :");

        bloodlabel.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        bloodlabel.setForeground(new java.awt.Color(255, 255, 255));
        bloodlabel.setText("OTHER :");

        othertxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        drugtxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        BPTxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        sugartxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DONOR REQUESTS DOCTOR ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrganList, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonorLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(druglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sugarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(othertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(drugtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sugartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonorTCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrganList, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DonorLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonorTCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sugartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sugarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(druglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(othertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        populateDonateTable();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        if(((String)OrganList.getSelectedItem()).equalsIgnoreCase("--Select--"))
        {
            JOptionPane.showMessageDialog(null,"Please select the organ you wish to donate");
            return;
        }
        else if(sugarlabel.getText().equals("") ||
                BPTxt.getText().equals("") ||
                othertxt.getText().equals("") ||
                drugtxt.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"Please fill all you medical details!!");
                        return;
        }
        else{
            String message = (String)OrganList.getSelectedItem();
            String Sugar=this.sugartxt.getText();
            String BP= this.BPTxt.getText();
            String drug=this.drugtxt.getText();
            String other= this.othertxt.getText();
            DonorOrganWorkRequest request = new DonorOrganWorkRequest();
            
            request.setMessage(message);
            request.setSender(account);
            request.setStatus("Sent");
            request.setRole("Donor");
            request.setSugar(Sugar);
            request.setBp(BP);
            request.setDrug(drug);
            request.setOther(other);
           
        Organizations org = null;
     
                
          for(Network network: System.getNetworkList()) {
             for(Enterprise enterprise: network.getEp().getEnterpriselist())
             {
                for (Organizations organization : enterprise.getOrganizationdir().getOrganizationList()){
                    if(network.equals(DonorLocationComboBox.getSelectedItem())){
                        if(enterprise.equals(DonorTCComboBox.getSelectedItem())){
                            if (organization instanceof DoctorOrganization){
                                org = organization;
                                break;
                            }
                        }
                
                     }
                 }
           }
        }
        if (org!=null)
        {
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null,"Your request has been initiated, please check your status on view details");
            populateDonateTable();
            try{
            Email emailConfig= new Email();
            Properties smtpProperties = emailConfig.loadProperties();
            String email = account.getUsername();
            emailConfig.sendEmail(smtpProperties, email, "Request Initiated", "Your request has being sent to the Transplantation center");
        }
            catch(Exception ex){
                
            }
        }
        if(org==null)
        {
            JOptionPane.showMessageDialog(null,"There was no Doctors Organization in the Transplantation Center  you have Selected !");
            return;
        }
            
        }
        
                        
    }//GEN-LAST:event_submitbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout)RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_backbtnActionPerformed

    private void DonorLocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorLocationComboBoxActionPerformed
        // TODO add your handling code here:
        
         Network network =(Network)DonorLocationComboBox.getSelectedItem();
        
        if (network != null){
            populateTC(network);}
    }//GEN-LAST:event_DonorLocationComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BPLabel;
    private javax.swing.JTextField BPTxt;
    private javax.swing.JComboBox DonorLocationComboBox;
    private javax.swing.JComboBox DonorTCComboBox;
    private javax.swing.JTable DonorWorkRequestJTable;
    private javax.swing.JComboBox<String> OrganList;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bloodlabel;
    private javax.swing.JLabel druglabel;
    private javax.swing.JTextField drugtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField othertxt;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel sugarlabel;
    private javax.swing.JTextField sugartxt;
    // End of variables declaration//GEN-END:variables
}
