/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InsuranceCompany;

import Business.Enterprise.Enterprise;
import Business.Organizations.Organizations;
import Business.Role.Role;
import Business.User.User;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanskruti
 */
public class ManageAgent extends javax.swing.JPanel {

    /**
     * Creates new form ManageAgent
     */
    private JPanel RightPanel;
    private Enterprise enterprise;
    public ManageAgent(JPanel RightPanel, Enterprise enterprise) {
        initComponents();
        this.RightPanel=RightPanel;
        this.enterprise=enterprise;
        popOrganizationComboBox();
        popData();
    }
     public void popOrganizationComboBox() {
        organizationDocJComboBox.removeAllItems();

        for (Organizations organization : enterprise.getOrganizationdir().getOrganizationList()) {
            organizationDocJComboBox.addItem(organization);
        }
    }
public void populateDoctorComboBox(Organizations organization){
        DoctorJComboBox.removeAllItems();
        
        for (User user : organization.getUserDirectory().getUserList()){
            DoctorJComboBox.addItem(user);
        }
    }

    private void populateRoleComboBox(Organizations organization){
        roleDJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            roleDJComboBox.addItem(role);
        }
    }
    
    public void popData() {

        DefaultTableModel model = (DefaultTableModel) doctorJTable.getModel();

        model.setRowCount(0);

        for (Organizations organization : enterprise.getOrganizationdir().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccounts()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) doctorJTable.getModel()).addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        organizationDocJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        DoctorJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        roleDJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        docpasswordJTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        SecurityQuestion = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        SecurityAnsTxt = new javax.swing.JTextField();
        backjButton1 = new javax.swing.JButton();
        UserLable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        createUserJButton.setBackground(new java.awt.Color(0, 153, 153));
        createUserJButton.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        createUserJButton.setForeground(new java.awt.Color(255, 255, 255));
        createUserJButton.setText("CREATE");
        createUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserJButtonActionPerformed(evt);
            }
        });

        doctorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doctorJTable);

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ORGANIZATION :");

        organizationDocJComboBox.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        organizationDocJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationDocJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationDocJComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGENT :");

        DoctorJComboBox.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        DoctorJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DoctorJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorJComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ROLE :");

        roleDJComboBox.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        roleDJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleDJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleDJComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME :");

        usernameJTextField.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        usernameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameJTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD :");

        docpasswordJTextField.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SECURITY QUESTION:");

        SecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mothers name ?", " What was the name of your elementary / primary school?", "What street did you live on in third grade?", " What is your oldest cousin's first and last name?" }));

        jLabel27.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SECURITY ANSWER :");

        SecurityAnsTxt.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N

        backjButton1.setBackground(new java.awt.Color(0, 153, 153));
        backjButton1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<<BACK");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        UserLable.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(156, 156, 156)
                        .addComponent(organizationDocJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(roleDJComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoctorJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(docpasswordJTextField)
                                    .addComponent(SecurityQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SecurityAnsTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createUserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserLable, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationDocJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoctorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleDJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(UserLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docpasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(SecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(SecurityAnsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserJButton)
                    .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonActionPerformed
        String userName = usernameJTextField.getText();
        String password = docpasswordJTextField.getText();
        Organizations organization = (Organizations) organizationDocJComboBox.getSelectedItem();
        User user = (User) DoctorJComboBox.getSelectedItem();
        Role role = (Role) roleDJComboBox.getSelectedItem();

        String PATTERN= "^[a-zA-Z0-9_]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match= patt.matcher(usernameJTextField.getText());
        
        if(usernameJTextField.getText().isEmpty() || docpasswordJTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter the username and password!");
            return;
        }
        else if(!match.matches()){
            JOptionPane.showMessageDialog(null,"Please enter a proper email address");
            return;
        }
        else{
            if(organization.getUserAccountDirectory().checkIfUsernameIsUnique(userName)){
                UserAccount ua=organization.getUserAccountDirectory().createUserAccount(userName, password, user, role);
                ua.setSecurityQ((String)SecurityQuestion.getSelectedItem());
                ua.setSecurityA(SecurityAnsTxt.getText());
                
                popData();

                JOptionPane.showMessageDialog(null, "agent registered successfully!");

                usernameJTextField.setText("");
                docpasswordJTextField.setText("");

            }

            else{
                JOptionPane.showMessageDialog(null, "This UserName Already Exists !");
            }

        }

    }//GEN-LAST:event_createUserJButtonActionPerformed

    private void organizationDocJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationDocJComboBoxActionPerformed
        Organizations organization = (Organizations) organizationDocJComboBox.getSelectedItem();
        if (organization != null){
            populateDoctorComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_organizationDocJComboBoxActionPerformed

    private void DoctorJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorJComboBoxActionPerformed

    private void roleDJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleDJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleDJComboBoxActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void usernameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameJTextFieldKeyTyped
        // TODO add your handling code here:
        String PATTERN= "^[a-zA-Z0-9_]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match= patt.matcher(usernameJTextField.getText());
        if(!match.matches())
        {
        UserLable.setText("Username is incorrect");
        }
        else{
        UserLable.setText(null);
        } 
    }//GEN-LAST:event_usernameJTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DoctorJComboBox;
    private javax.swing.JTextField SecurityAnsTxt;
    private javax.swing.JComboBox<String> SecurityQuestion;
    private javax.swing.JLabel UserLable;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JTextField docpasswordJTextField;
    private javax.swing.JTable doctorJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationDocJComboBox;
    private javax.swing.JComboBox roleDJComboBox;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
